### ISSUE TITLE
请忽略

### ISSUE THREAD

**Issue by aiden0z** [insigniaapple/insigniaapple.github.io#2]
已不在需要。

**Comment by insigniaapple** [comment]
比赛结束后在qq群137358724中得到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "insigniaapple/insigniaapple.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 上午10:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[insigniaapple/insigniaapple.github.io] 【紧急】请教关于第十三届蓝桥杯大赛的省赛真题 pdf 文件的问题 (Issue #2)





 
您好，我是蓝桥杯大赛组委会成员，我们发现在您这个仓库中有一个 CB.pdf 文件，显示为第十三届蓝桥杯大赛的省赛真题。
 
想和您进一步确认下，该文件是如何获取的，如果方便的可以发送到邮箱 ***@***.***，或者直接联系我 13241887629，十分感谢。
